# Generated by Django 4.2.11 on 2026-03-09 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import h5media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('file_path', models.CharField(blank=True, max_length=250)),
                ('type', models.CharField(blank=True, choices=[('e', 'Podcast Episode'), ('c', 'Audiobook Chapter'), ('t', 'Album Track')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(default='', max_length=500)),
                ('rss', models.URLField(default='', max_length=500, unique=True)),
                ('description', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_playing', models.JSONField(default=dict)),
                ('queue', models.JSONField(default=h5media.models.profile_queue_default)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('contents', models.JSONField(default=h5media.models.playlist_contents_default)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='h5media.mediafile')),
                ('url', models.URLField(default='', max_length=500, unique=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='h5media.podcast')),
            ],
            options={
                'abstract': False,
            },
            bases=('h5media.mediafile',),
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='h5media.mediafile')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='h5media.album')),
            ],
            options={
                'abstract': False,
            },
            bases=('h5media.mediafile',),
        ),
        migrations.CreateModel(
            name='AudiobookChapter',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='h5media.mediafile')),
                ('chapter', models.IntegerField(default=0)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='h5media.audiobook')),
            ],
            options={
                'unique_together': {('audiobook', 'chapter')},
            },
            bases=('h5media.mediafile',),
        ),
    ]
