# Generated by Django 4.2.11 on 2024-08-25 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h5media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_files', to='h5media.mediafile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_queue', to='h5media.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
