# Generated by Django 4.2.11 on 2024-04-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='rss',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='podcast',
            name='website',
            field=models.URLField(default='', max_length=500),
        ),
    ]
