# Generated by Django 4.2.11 on 2024-08-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5media', '0002_mediaqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaqueue',
            name='order',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name='mediaqueue',
            unique_together={('profile', 'media_file', 'order')},
        ),
    ]
