# Generated by Django 4.2.11 on 2024-11-15 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('h5media', '0003_mediaqueue_order_alter_mediaqueue_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='queue',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='podcasts_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MediaQueue',
        ),
    ]
