# Generated by Django 4.2.11 on 2026-01-23 01:12

from django.db import migrations, models
import django.db.models.deletion
import h5media.models


class Migration(migrations.Migration):

    dependencies = [
        ('h5media', '0004_profile_queue_alter_mediafile_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='type',
            field=models.CharField(blank=True, choices=[('e', 'Podcast Episode'), ('c', 'Audiobook Chapter'), ('t', 'Album Track')], max_length=1),
        ),
        migrations.AddField(
            model_name='playlist',
            name='contents',
            field=models.JSONField(default=h5media.models.playlist_contents_default),
        ),
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='now_playing',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_path',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='queue',
            field=models.JSONField(default=h5media.models.profile_queue_default),
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='h5media.mediafile')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='h5media.album')),
            ],
            options={
                'abstract': False,
            },
            bases=('h5media.mediafile',),
        ),
        migrations.CreateModel(
            name='AudiobookChapter',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='h5media.mediafile')),
                ('chapter', models.IntegerField(default=0)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='h5media.audiobook')),
            ],
            options={
                'unique_together': {('audiobook', 'chapter')},
            },
            bases=('h5media.mediafile',),
        ),
    ]
